---
title: Mayor's Task Force on Institutional Racism and Systemic Inequities
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: "/institutional-racism"
permalink: pretty
theme: jekyll-theme-cayman
exclude:
- Gemfile
